### ISSUE TITLE
ArduinoConnector for GUI

### ISSUE THREAD

**Issue by 8A3p7** [kbMSU/PySiento#26]
HI, someone who is doing the ArduinoConnector, the current file is just a script, I can't use it. I suggest to create a class interface first, then I can just use the interface in the graph drawing window.

**Comment by amirhzz** [comment]
HI, since we still don't have a framework yet that will not be possible.

**Comment by amirhzz** [comment]
I have put it in a new file called ArduinoConnector_class but still we don't have a framework, which is hideous.

**Comment by kbMSU** [comment]
This task is finished. I will be closing this task.
