### ISSUE TITLE
Investigate if VS can build forms using Python 

### ISSUE THREAD

**Issue by m8383** [kbMSU/PySiento#35]

**Comment by m8383** [comment]
Investigating

**Comment by m8383** [comment]
It appears you can build forms in VS with Python using the .NET implementation of Python which is ideal for interfacing with C#. This would be the alternative approach - to design the form in C# where we could then use this as a platform class for the IronPython project. However, VS does not have the forms designer for Python tools.

**Comment by edbrax** [comment]
No forms designer makes it somewhat difficult and .NET is probably going to be a problem for cross-platform.
