### ISSUE TITLE
Suggest change button labelled "Flash" to "Start Sensor Box" or similar

### ISSUE THREAD

**Issue by edbrax** [kbMSU/PySiento#4]
Most laypeople will not understand what Flash means.

**Comment by 8A3p7** [comment]
Hi, actually it's not start the device. it's burning the programming into the device. Should I use "download" or "upload" ?

**Comment by edbrax** [comment]
In that case I would suggest "Reset the eHealth Device".

**Comment by kbMSU** [comment]
I have changed the name on the UI.
